apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: appstudio-registry-exporter
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  namespace: appstudio-registry-exporter
  annotations:
    kubernetes.io/service-account.name: metrics-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-exporter-role-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-exporter-role-binding-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-exporter-role-metrics-reader
subjects:
- kind: ServiceAccount
  name: metrics-reader
  namespace: appstudio-registry-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: registry-exporter-ds-podmonitor
  namespace: appstudio-registry-exporter
spec:
  podMetricsEndpoints:
  - interval: 2m
    path: /metrics
    port: https
    scheme: https
    bearerTokenSecret:
      name: "metrics-reader"
      key: token
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - appstudio-registry-exporter
  selector:
    matchLabels:
      app: registry-exporter
