apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-mintmaker-controller-availability-alerting-rules
  labels:
    tenant: rhtap

spec:
  groups:
  - name: mintmaker-controller-availability
    interval: 1m
    rules:
    - alert: MintMakerControllerDown
      expr: |
        konflux_up{
          namespace="mintmaker",
          check="replicas-available",
          service="mintmaker-controller-manager"
        } != 1
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          MintMaker controller is down in cluster {{ $labels.source_cluster }}
        description: >
          The MintMaker controller pod has been down for 5min in cluster {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S078T8TMQP5>
        team: mintmaker
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/mintmaker/faq.md

  - name: mintmaker-cache-availability
    interval: 1m
    rules:
    - alert: MintMakerCacheDown
      expr: |
        konflux_up{
          namespace="mintmaker",
          check="replicas-available",
          service="redis"
        } != 1
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          MintMaker cache is down in cluster {{ $labels.source_cluster }}
        description: >
          The MintMaker cache pod (redis) has been down for 5min in cluster {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S078T8TMQP5>
        team: mintmaker
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/mintmaker/faq.md
