apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-seb-created-to-ready-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: seb-created-to-ready
    interval: 1m
    rules:
    - alert: SebCreatedToReady
      expr: |
        (
          (
            increase(integration_svc_seb_created_to_ready_seconds_bucket{le="+Inf"}[5m])
            - ignoring(le)
            increase(integration_svc_seb_created_to_ready_seconds_bucket{le="120"}[5m])
          ) / ignoring(le)
          increase(integration_svc_seb_created_to_ready_seconds_bucket{le="+Inf"}[5m])
        ) > 0.10
      for: 1m
      labels:
        severity: warning
        slo: true
      annotations:
        summary: >-
          Snapshot Environment Binding created to ready time exceeded
        description: >
          Time from Snapshot Environment Binding created to marked as
          ready has been over 120s for more than 10% of requests during
          the last 5 minutes on cluster {{ $labels.source_cluster }}
        runbook_url: https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/integration-service/seb_created_to_ready.md
