apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-release-service-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: release_service_alerts
    interval: 1m

    rules:
    # record rules for `ReleaseServicePreProcessingDurationSeconds`
    - record: rate_of_release_pre_processing_duration_seconds_shorter_than_10s_per_10m
      expr: sum by (job,source_cluster) (rate(release_pre_processing_duration_seconds_bucket{le="10"}[10m]))

    # preprocessing for more than 60 seconds
    - record: rate_of_release_pre_processing_duration_seconds_shorter_than_60s_per_10m
      expr: sum by (job,source_cluster) (rate(release_pre_processing_duration_seconds_bucket{le="60"}[10m]))

    - record: rate_of_release_pre_processing_duration_seconds_counter_per_10m
      expr: sum by (job,source_cluster) (rate(release_pre_processing_duration_seconds_count[10m]) > 0)

    # record rules for `ReleaseServiceValidationDurationSeconds`
    - record: rate_of_release_validation_duration_seconds_shorter_than_5s_per_10m
      expr: sum by (job,source_cluster) (rate(release_validation_duration_seconds_bucket{le="5"}[10m]))

    - record: rate_of_release_validation_duration_seconds_counter_per_10m
      expr: sum by (job,source_cluster) (rate(release_validation_duration_seconds_count[10m]) > 0)

    - alert: ReleaseServiceValidationDurationSeconds
      expr: |
        (
          rate_of_release_validation_duration_seconds_shorter_than_5s_per_10m / rate_of_release_validation_duration_seconds_counter_per_10m
        ) < 0.90
      for: 15m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          90% of Releases must be validated under 5 seconds
        description: >-
          Release service is failing to run the validations under 5 seconds for 90% of releases
        alert_team_handle: <!subteam^S03SVBS426R>
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/release-validation-latency.md?ref_type=heads
        team: release

    - alert: ReleaseServicePreProcessingDurationSeconds
      expr: |
        (
          rate_of_release_pre_processing_duration_seconds_shorter_than_60s_per_10m / rate_of_release_pre_processing_duration_seconds_counter_per_10m
        ) < 0.90
      for: 15m
      labels:
        severity: high
        slo: "false"
      annotations:
        summary: >-
          90% of Releases must start processing under 10 seconds
        description: >-
          Release service is failing to start processing under 10 seconds for 90% of releases
        alert_routing_key: release-service
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/release-processing-latency.md?ref_type=heads
        team: release

    - alert: ReleaseServiceControllerManagerPodNotReady
      expr: |
        sum by (source_cluster, namespace) (kube_pod_container_status_ready{container="manager",namespace="release-service",source_cluster=~"stone-prd-rh01|stone-prod-p02"}) == 0
      for: 10m
      labels:
        severity: high
      annotations:
        summary: >-
          The Release Service Controller Manager is down in the {{ $labels.source_cluster }} for the last 10 minutes
        description: >-
          The Release Service Controller Manager is down in the {{ $labels.source_cluster }} for the last 10 minutes
        alert_routing_key: "{{ $labels.namespace }}"
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/release-service/release-controller-availability.md?ref_type=heads
        team: release
