apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-latency-image-repository-provision-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: latency-image-repository-provision
    interval: 1m
    rules:
    - alert: LatencyImageRepositoryProvision
      expr: |
        (
          (
            increase(redhat_appstudio_imagecontroller_image_repository_provision_time_bucket{le="+Inf"}[5m])
            - ignoring(le)
            increase(redhat_appstudio_imagecontroller_image_repository_provision_time_bucket{le="30"}[5m])
          ) / ignoring(le)
          increase(redhat_appstudio_imagecontroller_image_repository_provision_time_bucket{le="+Inf"}[5m])
        ) > 0.05
      for: 1m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          Latency of image repository provision time exceeded
        description: >
          Time taken to provision image repository has been over
          30s for more than 5% of requests during the last 5 minutes on cluster
          {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S0500D143S8>
        team: build
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/image-controller/latency_image_repository_provision.md
