apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-application-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: application_alerts
    interval: 1m
    rules:
    - alert: ApplicationDeletionErrors
      expr: |
        (increase(has_application_failed_deletion_total[1h]))
        /
        (increase(has_application_deletion_total[1h]))  > 0.05
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          HAS is experiencing application deletion failures of >5%
        description: >-
          Application controller in Pod {{ $labels.pod }} for namespace
          {{ $labels.namespace }} on cluster {{ $labels.source_cluster }} is failing to
          successfully delete at least 95% of applications over the past hour
        alert_team_handle: <!subteam^S04MSCVRF4Z>
        team: has
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/has/application-delete-failed.md
    - alert: ApplicationCreationErrors
      expr: |
        (increase(has_application_failed_creation_total[1h]))
        /
        (increase(has_application_creation_total[1h])) > 0.05
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          HAS is experiencing application creation failures of >5%
        description: >-
          Application controller in Pod {{ $labels.pod }} for namespace
          {{ $labels.namespace }} on cluster {{ $labels.source_cluster }} is failing to
          successfully create at least 95% of applications over the past hour
        alert_team_handle: <!subteam^S04MSCVRF4Z>
        team: has
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/has/application-create-failed.md
