apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-high-memory-usage-alert-rule
  labels:
    tenant: rhtap
spec:
  groups:
  - name: high_memory_usage_alert
    interval: 5m
    rules:
    - alert: HighMemoryUsageAlert
      expr: |
        100 * ( sum by (namespace,source_cluster) (namespace_container:container_memory_working_set_bytes) (.*-tenant|.*-env|openshift-.*|kube-.*|default|tekton-ci|build-templates-e2e|konflux-ci|mintmaker)"}
        / sum by (namespace,source_cluster) (namespace_memory:kube_pod_container_resource_requests:sum) (.*-tenant|.*-env|openshift-.*|kube-.*|default|tekton-ci|build-templates-e2e|konflux-ci|mintmaker)"}) * 100 > 90

      expr: |
        70 * (sum by (namespace,source_cluster,pod,tenant_id)(namespace_memory:kube_pod_container_resource_limits:sum))
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} has high memory usage"
        description: "Pod {{ $labels.pod }} for namespace {{ $labels.namespace }} on cluster {{ $labels.source_cluster }} has high memory usage"
        alert_routing_key: '{{ $labels.namespace }}'
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/sre/alert-rule-HighMemoryAlertUsage.md
