apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pulp-access-controller-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: pulp-access-controller-availability
    interval: 1m
    rules:
    - alert: PulpAccessControllerDown
      expr: |
        konflux_up{
          namespace="pulp-access-controller",
          check="replicas-available",
          service="pulp-access-operator"
        } != 1
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          pulp-access-controller is down in cluster {{ $labels.source_cluster }}
        description: >
          The pulp-access-controller pod has been down for 5min in cluster {{ $labels.source_cluster }}
        team: build
        alert_team_handle: <!subteam^S03DM1RL0TF>
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pulp-access-controller/pulp-access-controller-availability.md