apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-registry-exporter-availability-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: registry-exporter-availability
    interval: 1m
    rules:
    - alert: RegistryExporterDown
      expr: |
        konflux_up{service="registry-exporter"} != 1
      for: 15m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          Registry exporter check failed for registry {{ $labels.check }} in cluster {{ $labels.source_cluster }}
        description: >-
          The registry exporter has failed to successfully test registry {{ $labels.check }} in cluster {{ $labels.source_cluster }}.
          All registry test operations (pull, push, metadata, authentication) have been failing for 15 minutes.
        alert_team_handle: '<!subteam^S07SW2EEW3D>'
        team: o11y
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/o11y/alert-rules/alert-rule-RegistryExporter.md
