apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pipeline-to-snapshot-exceeded-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: pipeline-to-snapshot-exceeded
    interval: 1m
    rules:
    - alert: PipelineRunToSnapshotExceeded
      expr: |
       (
        (
         increase(integration_svc_response_seconds_bucket{le="+Inf"}[10m])
         - ignoring(le)
         increase(integration_svc_response_seconds_bucket{le="30"}[10m])
        ) / ignoring(le)
        increase(integration_svc_response_seconds_bucket{le="+Inf"}[10m])
       ) > 0.10
      for: 10m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          PipelineRunFinish to SnapshotInProgress time exceeded
        description: >
          Time from pipeline run finished to snapshot marked in progress has been over
          30s for more than 10% of requests during the last 10 minutes and has not improved for 10 minutes
          on cluster {{ $labels.source_cluster }}
        alert_routing_key: integration-service
        runbook_url: https://gitlab.cee.redhat.com/rhtap/docs/sop/-/blob/main/integration-service/pipeline_to_snapshot_exceeded.md
