apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-latency-pac-provision-alerting-rules
  labels:
    tenant: rhtap
spec:
  groups:
  - name: latency-pac-provision
    interval: 1m
    rules:
    - alert: LatencyPacProvision
      expr: |
        (
          (
            increase(redhat_appstudio_buildservice_PaC_configuration_time_bucket{le="+Inf"}[5m])
            - ignoring(le)
            increase(redhat_appstudio_buildservice_PaC_configuration_time_bucket{le="20"}[5m])
          ) / ignoring(le)
          increase(redhat_appstudio_buildservice_PaC_configuration_time_bucket{le="+Inf"}[5m])
        ) > 0.05
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          Latency of component PaC provision time exceeded
        description: >
          Time taken from PaC provision request till Component is provisioned for PaC builds has been over
          20s for more than 5% of requests during the last 5 minutes on cluster
          {{ $labels.source_cluster }}
        alert_team_handle: <!subteam^S0500D143S8>
        team: build
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/build-service/latency_pac_provision.md
