apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-spi-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: serviceprovider_alerts
      interval: 1m
      rules:
        - alert: ServiceProvider5xxErrorsRate
          expr: |
            (
              sum without (status) (increase(redhat_appstudio_spi_service_provider_response_time_seconds_count{status=~"5.."}[1h]))
              or sum without (status) (increase(redhat_appstudio_spi_service_provider_response_time_seconds_count[1h])) * 0
            )
            /
            sum without (status) (increase(redhat_appstudio_spi_service_provider_response_time_seconds_count[1h])) > 0.10
          for: 5m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              SPI is experiencing 5xx errors from service provider {{ $labels.sp }} of >10%
            description: >-
              Application controller in Pod {{ $labels.pod }} for namespace
              {{ $labels.namespace }} on instance {{ $labels.source_cluster }} having a
              {{ $value | humanizePercentage }} of 5xx errors from service provider {{ $labels.sp }} for latest 60 minutes
            alert_team_handle: <!subteam^SLRSHSU1K>
            team: spi
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/spi/alert-rule-serviceprovider5xxErrorsRate.md
